# -*- coding: utf-8 -*-
"""evaluate_data_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNkDW2pyAhpW2aGP95plZGvdb-_HfMMv
"""

from tensorflow.keras.models import load_model
from PIL import Image
import os
import pathlib
from tensorflow.keras.preprocessing import image_dataset_from_directory
# -------------------------------------------------------------------------------------------------
data_test = image_dataset_from_directory(val_dir, label_mode='categorical', image_size=(224, 224), batch_size=64)

#model.compile(optimizer=optimizer_init(), loss="categorical_crossentropy", metrics=model.compile(optimizer=optimizer_init(), loss="categorical_crossentropy", metrics=['accuracy']))
model = Sequential()

model.add(Conv2D(32, (3,3), input_shape=(224,224,3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Conv2D(128, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Conv2D(256, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Dropout(0.4))

model.add(Conv2D(512, (1,1), activation='relu'))
#model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Flatten())
model.add(Dropout(0.4))

model.add(Dense(units=13, activation='relu'))
model.add(Dense(13, activation='softmax'))
model = load_model("model.h5")

model.summary()
print('Data: TEST')
print(model.evaluate(data_test, verbose=-1))